In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
'''
pd.get_option("display.max_rows")
pd.set_option("display.max_rows", None)
'''
pd.get_option("display.max_columns")
pd.set_option("display.max_columns", None)

In [3]:
url = 'https://raw.githubusercontent.com/brandonsalter/data/main/Jets_1960-2021_pre-clean.csv'
df = pd.read_csv(url) 
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts
0,1,Sun,September 11,1960.0,NaN,W,NaN,1-0,NaN,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN
1,2,Sat,September 17,NaN,NaN,L,NaN,1-1,NaN,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN
2,3,Fri,September 23,NaN,NaN,W,NaN,2-1,NaN,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN
3,4,Sun,October 2,NaN,NaN,W,NaN,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN
4,5,Sun,October 9,NaN,NaN,L,NaN,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,14,Sun,December 12,NaN,1:00PM ET,L,NaN,3-10,NaN,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,NaN,21.0,344.0,141.0,203.0,NaN,-10.95,-8.42,4.28
1017,15,Sun,December 19,NaN,1:00PM ET,L,NaN,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79
1018,16,Sun,December 26,NaN,1:00PM ET,W,NaN,4-11,NaN,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,NaN,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81
1019,17,Sun,January 2,2022.0,1:00PM ET,L,NaN,4-12,NaN,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20
1020,18,Sun,January 9,NaN,1:00PM ET,L,NaN,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,NaN,25.0,424.0,254.0,170.0,NaN,-23.07,-8.18,14.05

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Week             1007 non-null   object
 1   Day              974 non-null    object
 2   Date             988 non-null    object
 3   Year             63 non-null     float64
 4   Time             831 non-null    object
 5   Win/Loss         974 non-null    object
 6   OT               49 non-null     object
 7   Rec              974 non-null    object
 8   Away             493 non-null    object
 9   Opp              1007 non-null   object
 10  Score_Tm         974 non-null    float64
 11  Score_Opp        974 non-null    float64
 12  Off_1stD         974 non-null    float64
 13  Off_TotYd        974 non-null    float64
 14  Off_PassY        973 non-null    float64
 15  Off_RushY        974 non-null    float64
 16  Off_TO           815 non-null    float64
 17  Def_1stD         974 non-null    float64
 18  Def_TotYd        974 non-null    float64
 19  Def_PassY        972 non-null    float64
 20  Def_RushY        974 non-null    float64
 21  Def_TO           816 non-null    float64
 22  Offense_Exp_Pts  463 non-null    float64
 23  Defense_Exp_Pts  463 non-null    float64
 24  Sp_Tms_Exp_Pts   463 non-null    float64
dtypes: float64(16), object(9)
memory usage: 199.5+ KB

In [5]:
df.Year.unique()

array([1960.,   nan, 1961., 1962., 1963., 1964., 1965., 1966., 1967.,
       1968., 1969., 1970., 1971., 1972., 1973., 1974., 1975., 1976.,
       1977., 1978., 1979., 1980., 1981., 1982., 1983., 1984., 1985.,
       1986., 1987., 1988., 1989., 1990., 1991., 1992., 1993., 1994.,
       1995., 1996., 1997., 1998., 1999., 2000., 2001., 2002., 2003.,
       2004., 2005., 2006., 2007., 2008., 2009., 2010., 2011., 2012.,
       2013., 2014., 2015., 2016., 2017., 2018., 2019., 2020., 2021.,
       2022.])

In [6]:
df.loc[:,['Year']] = df.loc[:,'Year'].ffill()
df['Year'] = df['Year'].astype('int')
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts
0,1,Sun,September 11,1960,NaN,W,NaN,1-0,NaN,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN
1,2,Sat,September 17,1960,NaN,L,NaN,1-1,NaN,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN
2,3,Fri,September 23,1960,NaN,W,NaN,2-1,NaN,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN
3,4,Sun,October 2,1960,NaN,W,NaN,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN
4,5,Sun,October 9,1960,NaN,L,NaN,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,14,Sun,December 12,2021,1:00PM ET,L,NaN,3-10,NaN,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,NaN,21.0,344.0,141.0,203.0,NaN,-10.95,-8.42,4.28
1017,15,Sun,December 19,2021,1:00PM ET,L,NaN,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79
1018,16,Sun,December 26,2021,1:00PM ET,W,NaN,4-11,NaN,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,NaN,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81
1019,17,Sun,January 2,2022,1:00PM ET,L,NaN,4-12,NaN,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20
1020,18,Sun,January 9,2022,1:00PM ET,L,NaN,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,NaN,25.0,424.0,254.0,170.0,NaN,-23.07,-8.18,14.05

In [7]:
df.Year.unique()

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [8]:
df.Week.unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '12', '13',
       '14', '15', '11', '16', '17', nan, 'Championship', 'SuperBowl',
       'Division', 'Wild Card', 'Conf. Champ.', '18'], dtype=object)

In [9]:
df = df[df.Week.notnull()]
df.Week.unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '12', '13',
       '14', '15', '11', '16', '17', 'Championship', 'SuperBowl',
       'Division', 'Wild Card', 'Conf. Champ.', '18'], dtype=object)

In [10]:
df = df[df.Week != 'Championship']
df = df[df.Week != 'SuperBowl']
df = df[df.Week != 'Division']
df = df[df.Week != 'Wild Card']
df = df[df.Week != 'Conf. Champ.']
df.Week.unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '12', '13',
       '14', '15', '11', '16', '17', '18'], dtype=object)

In [11]:
df.Opp.unique()

array(['Buffalo Bills', 'Boston Patriots', 'Denver Broncos',
       'Dallas Texans', 'Houston Oilers', 'Oakland Raiders',
       'Los Angeles Chargers', 'San Diego Chargers', 'Kansas City Chiefs',
       'Miami Dolphins', 'Cincinnati Bengals', 'Cleveland Browns',
       'Baltimore Colts', 'New York Giants', 'Pittsburgh Steelers',
       'Los Angeles Rams', 'Minnesota Vikings', 'St. Louis Cardinals',
       'New England Patriots', 'San Francisco 49ers', 'Dallas Cowboys',
       'Washington Redskins', 'Detroit Lions', 'New Orleans Saints',
       'Green Bay Packers', 'Atlanta Falcons', 'Philadelphia Eagles',
       'Chicago Bears', 'Tampa Bay Buccaneers', 'Seattle Seahawks',
       'Indianapolis Colts', 'Los Angeles Raiders', 'Bye Week',
       'Jacksonville Jaguars', 'Carolina Panthers', 'St. Louis Rams',
       'Arizona Cardinals', 'Baltimore Ravens', 'Tennessee Oilers',
       'Houston Texans', 'Tennessee Titans', 'Las Vegas Raiders'],
      dtype=object)

In [12]:
df = df[df.Opp != 'Bye Week']
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts
0,1,Sun,September 11,1960,NaN,W,NaN,1-0,NaN,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN
1,2,Sat,September 17,1960,NaN,L,NaN,1-1,NaN,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN
2,3,Fri,September 23,1960,NaN,W,NaN,2-1,NaN,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN
3,4,Sun,October 2,1960,NaN,W,NaN,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN
4,5,Sun,October 9,1960,NaN,L,NaN,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,14,Sun,December 12,2021,1:00PM ET,L,NaN,3-10,NaN,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,NaN,21.0,344.0,141.0,203.0,NaN,-10.95,-8.42,4.28
1017,15,Sun,December 19,2021,1:00PM ET,L,NaN,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79
1018,16,Sun,December 26,2021,1:00PM ET,W,NaN,4-11,NaN,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,NaN,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81
1019,17,Sun,January 2,2022,1:00PM ET,L,NaN,4-12,NaN,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20
1020,18,Sun,January 9,2022,1:00PM ET,L,NaN,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,NaN,25.0,424.0,254.0,170.0,NaN,-23.07,-8.18,14.05

In [13]:
df = df.reset_index(drop=True)
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts
0,1,Sun,September 11,1960,NaN,W,NaN,1-0,NaN,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN
1,2,Sat,September 17,1960,NaN,L,NaN,1-1,NaN,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN
2,3,Fri,September 23,1960,NaN,W,NaN,2-1,NaN,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN
3,4,Sun,October 2,1960,NaN,W,NaN,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN
4,5,Sun,October 9,1960,NaN,L,NaN,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,Sun,December 12,2021,1:00PM ET,L,NaN,3-10,NaN,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,NaN,21.0,344.0,141.0,203.0,NaN,-10.95,-8.42,4.28
945,15,Sun,December 19,2021,1:00PM ET,L,NaN,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79
946,16,Sun,December 26,2021,1:00PM ET,W,NaN,4-11,NaN,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,NaN,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81
947,17,Sun,January 2,2022,1:00PM ET,L,NaN,4-12,NaN,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20
948,18,Sun,January 9,2022,1:00PM ET,L,NaN,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,NaN,25.0,424.0,254.0,170.0,NaN,-23.07,-8.18,14.05

In [14]:
df.loc[:,['OT']] = df.loc[:,'OT'].fillna(0)
df.loc[:,['Away']] = df.loc[:,'Away'].fillna(0)
df.loc[:,['Off_TO']] = df.loc[:,'Off_TO'].fillna(0)
df.loc[:,['Def_TO']] = df.loc[:,'Def_TO'].fillna(0)
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts
0,1,Sun,September 11,1960,NaN,W,0,1-0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN
1,2,Sat,September 17,1960,NaN,L,0,1-1,0,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN
2,3,Fri,September 23,1960,NaN,W,0,2-1,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN
3,4,Sun,October 2,1960,NaN,W,0,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN
4,5,Sun,October 9,1960,NaN,L,0,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,Sun,December 12,2021,1:00PM ET,L,0,3-10,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,-10.95,-8.42,4.28
945,15,Sun,December 19,2021,1:00PM ET,L,0,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79
946,16,Sun,December 26,2021,1:00PM ET,W,0,4-11,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81
947,17,Sun,January 2,2022,1:00PM ET,L,0,4-12,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20
948,18,Sun,January 9,2022,1:00PM ET,L,0,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,-23.07,-8.18,14.05

In [15]:
df.isna().sum()

Week                 0
Day                  0
Date                 0
Year                 0
Time               140
Win/Loss             0
OT                   0
Rec                  0
Away                 0
Opp                  0
Score_Tm             0
Score_Opp            0
Off_1stD             0
Off_TotYd            0
Off_PassY            1
Off_RushY            0
Off_TO               0
Def_1stD             0
Def_TotYd            0
Def_PassY            2
Def_RushY            0
Def_TO               0
Offense_Exp_Pts    500
Defense_Exp_Pts    500
Sp_Tms_Exp_Pts     500
dtype: int64

In [16]:
df.loc[:,['Off_PassY']] = df.loc[:,'Off_PassY'].fillna(0)
df.loc[:,['Def_PassY']] = df.loc[:,'Def_PassY'].fillna(0)

In [17]:
df.isna().sum()

Week                 0
Day                  0
Date                 0
Year                 0
Time               140
Win/Loss             0
OT                   0
Rec                  0
Away                 0
Opp                  0
Score_Tm             0
Score_Opp            0
Off_1stD             0
Off_TotYd            0
Off_PassY            0
Off_RushY            0
Off_TO               0
Def_1stD             0
Def_TotYd            0
Def_PassY            0
Def_RushY            0
Def_TO               0
Offense_Exp_Pts    500
Defense_Exp_Pts    500
Sp_Tms_Exp_Pts     500
dtype: int64

In [18]:
df[['Month', 'Day']] = df['Date'].str.split(' ', 1, expand=True)
df

,Week,Day,Date,Year,Time,Win/Loss,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts,Month
0,1,11,September 11,1960,NaN,W,0,1-0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN,September
1,2,17,September 17,1960,NaN,L,0,1-1,0,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN,September
2,3,23,September 23,1960,NaN,W,0,2-1,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN,September
3,4,2,October 2,1960,NaN,W,0,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN,October
4,5,9,October 9,1960,NaN,L,0,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN,October
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,December 12,2021,1:00PM ET,L,0,3-10,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,-10.95,-8.42,4.28,December
945,15,19,December 19,2021,1:00PM ET,L,0,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79,December
946,16,26,December 26,2021,1:00PM ET,W,0,4-11,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81,December
947,17,2,January 2,2022,1:00PM ET,L,0,4-12,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20,January
948,18,9,January 9,2022,1:00PM ET,L,0,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,-23.07,-8.18,14.05,January

In [19]:
df = df.rename(columns={'Week': 'Week_of_Season',
          'Day': 'Day_of_Month',
           'Win/Loss': 'Win',
          })
df

,Week_of_Season,Day_of_Month,Date,Year,Time,Win,OT,Rec,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Offense_Exp_Pts,Defense_Exp_Pts,Sp_Tms_Exp_Pts,Month
0,1,11,September 11,1960,NaN,W,0,1-0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,NaN,NaN,NaN,September
1,2,17,September 17,1960,NaN,L,0,1-1,0,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,NaN,NaN,NaN,September
2,3,23,September 23,1960,NaN,W,0,2-1,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,NaN,NaN,NaN,September
3,4,2,October 2,1960,NaN,W,0,3-1,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,NaN,NaN,NaN,October
4,5,9,October 9,1960,NaN,L,0,3-2,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,NaN,NaN,NaN,October
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,December 12,2021,1:00PM ET,L,0,3-10,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,-10.95,-8.42,4.28,December
945,15,19,December 19,2021,1:00PM ET,L,0,3-11,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,-6.38,-2.65,1.79,December
946,16,26,December 26,2021,1:00PM ET,W,0,4-11,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,10.13,-8.72,4.81,December
947,17,2,January 2,2022,1:00PM ET,L,0,4-12,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,13.43,-17.50,-0.20,January
948,18,9,January 9,2022,1:00PM ET,L,0,4-13,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,-23.07,-8.18,14.05,January

In [20]:
df = df.drop(['Date', 'Rec', 'Offense_Exp_Pts', 'Defense_Exp_Pts', 'Sp_Tms_Exp_Pts'], axis=1)
df

,Week_of_Season,Day_of_Month,Year,Time,Win,OT,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Month
0,1,11,1960,NaN,W,0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,September
1,2,17,1960,NaN,L,0,0,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,September
2,3,23,1960,NaN,W,0,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,September
3,4,2,1960,NaN,W,0,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,October
4,5,9,1960,NaN,L,0,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,October
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,2021,1:00PM ET,L,0,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,December
945,15,19,2021,1:00PM ET,L,0,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,December
946,16,26,2021,1:00PM ET,W,0,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,December
947,17,2,2022,1:00PM ET,L,0,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,January
948,18,9,2022,1:00PM ET,L,0,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,January

In [21]:
df = df[['Week_of_Season','Month','Day_of_Month','Year','Time','Win','OT','Away','Opp','Score_Tm',
        'Score_Opp','Off_1stD','Off_TotYd','Off_PassY','Off_RushY','Off_TO','Def_1stD','Def_TotYd','Def_PassY',
         'Def_RushY','Def_TO']]
df

,Week_of_Season,Month,Day_of_Month,Year,Time,Win,OT,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO
0,1,September,11,1960,NaN,W,0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0
1,2,September,17,1960,NaN,L,0,0,Boston Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0
2,3,September,23,1960,NaN,W,0,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0
3,4,October,2,1960,NaN,W,0,@,Dallas Texans,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0
4,5,October,9,1960,NaN,L,0,@,Houston Oilers,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,December,12,2021,1:00PM ET,L,0,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0
945,15,December,19,2021,1:00PM ET,L,0,@,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0
946,16,December,26,2021,1:00PM ET,W,0,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0
947,17,January,2,2022,1:00PM ET,L,0,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0
948,18,January,9,2022,1:00PM ET,L,0,@,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0

'Boston Patriots' --> 'New England Patriots'

'Dallas Texans' --> 'Kansas City Chiefs'

'San Diego Chargers' --> 'Los Angeles Chargers'

'Baltimore Colts' --> 'Indianapolis Colts'

'St. Louis Cardinals' --> 'Arizona Cardinals'

'Washington Redskins' --> 'Washington Commanders'

'St. Louis Rams' --> 'Los Angeles Rams'

 
'Tennessee Oilers' --> 'Tennessee Titans'
'Houston Oilers' --> 'Tennessee Titans'

'Los Angeles Raiders' --> 'Las Vegas Raiders' 
'Oakland Raiders' --> 'Las Vegas Raiders'

In [22]:
df['Opp'] = df['Opp'].replace(['Boston Patriots', 'Dallas Texans', 'San Diego Chargers', 
                               'Baltimore Colts', 'St. Louis Cardinals', 'Washington Redskins', 
                               'St. Louis Rams'
                              ], 
                              ['New England Patriots', 'Kansas City Chiefs', 'Los Angeles Chargers', 
                               'Indianapolis Colts', 'Arizona Cardinals', 'Washington Commanders', 
                               'Los Angeles Rams'])

df['Opp'] = df['Opp'].replace(['Tennessee Oilers','Houston Oilers'
                              ], 
                              'Tennessee Titans')

df['Opp'] = df['Opp'].replace(['Los Angeles Raiders','Oakland Raiders'
                              ], 
                              'Las Vegas Raiders')

df.Opp.unique()

array(['Buffalo Bills', 'New England Patriots', 'Denver Broncos',
       'Kansas City Chiefs', 'Tennessee Titans', 'Las Vegas Raiders',
       'Los Angeles Chargers', 'Miami Dolphins', 'Cincinnati Bengals',
       'Cleveland Browns', 'Indianapolis Colts', 'New York Giants',
       'Pittsburgh Steelers', 'Los Angeles Rams', 'Minnesota Vikings',
       'Arizona Cardinals', 'San Francisco 49ers', 'Dallas Cowboys',
       'Washington Commanders', 'Detroit Lions', 'New Orleans Saints',
       'Green Bay Packers', 'Atlanta Falcons', 'Philadelphia Eagles',
       'Chicago Bears', 'Tampa Bay Buccaneers', 'Seattle Seahawks',
       'Jacksonville Jaguars', 'Carolina Panthers', 'Baltimore Ravens',
       'Houston Texans'], dtype=object)

In [23]:
len(df.Opp.unique()) # 32 teams minus the Jets

31

In [24]:
df['OT'] = df['OT'].replace(['OT'], 1)
df.OT.unique()

array([0, 1])

In [25]:
df['Away'] = df['Away'].replace(['@'], 1)
df.Away.unique()

array([0, 1])

In [26]:
df['Win'] = df['Win'].replace(['W','T','L'], [1,0,-1])
df.Win.unique()

array([ 1, -1,  0])

In [27]:
df

,Week_of_Season,Month,Day_of_Month,Year,Time,Win,OT,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO
0,1,September,11,1960,NaN,1,0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0
1,2,September,17,1960,NaN,-1,0,0,New England Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0
2,3,September,23,1960,NaN,1,0,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0
3,4,October,2,1960,NaN,1,0,1,Kansas City Chiefs,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0
4,5,October,9,1960,NaN,-1,0,1,Tennessee Titans,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,December,12,2021,1:00PM ET,-1,0,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0
945,15,December,19,2021,1:00PM ET,-1,0,1,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0
946,16,December,26,2021,1:00PM ET,1,0,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0
947,17,January,2,2022,1:00PM ET,-1,0,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0
948,18,January,9,2022,1:00PM ET,-1,0,1,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0

In [28]:
df = df.drop(['Time'], axis=1) # do something with time
df

,Week_of_Season,Month,Day_of_Month,Year,Win,OT,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO
0,1,September,11,1960,1,0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0
1,2,September,17,1960,-1,0,0,New England Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0
2,3,September,23,1960,1,0,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0
3,4,October,2,1960,1,0,1,Kansas City Chiefs,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0
4,5,October,9,1960,-1,0,1,Tennessee Titans,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,December,12,2021,-1,0,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0
945,15,December,19,2021,-1,0,1,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0
946,16,December,26,2021,1,0,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0
947,17,January,2,2022,-1,0,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0
948,18,January,9,2022,-1,0,1,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0

In [29]:
df.isna().sum()

Week_of_Season    0
Month             0
Day_of_Month      0
Year              0
Win               0
OT                0
Away              0
Opp               0
Score_Tm          0
Score_Opp         0
Off_1stD          0
Off_TotYd         0
Off_PassY         0
Off_RushY         0
Off_TO            0
Def_1stD          0
Def_TotYd         0
Def_PassY         0
Def_RushY         0
Def_TO            0
dtype: int64

In [30]:
month_mapping = {'January':1, 'February':2, 'March':3, 'April':4,
                 'May':5, 'June':6, 'July':7, 'August':8,
                 'September':9, 'October':10, 'November':11, 'December':12}
df = df.assign(
    Month = lambda x: x['Month'].map(month_mapping)
    )
df

,Week_of_Season,Month,Day_of_Month,Year,Win,OT,Away,Opp,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO
0,1,9,11,1960,1,0,0,Buffalo Bills,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0
1,2,9,17,1960,-1,0,0,New England Patriots,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0
2,3,9,23,1960,1,0,0,Denver Broncos,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0
3,4,10,2,1960,1,0,1,Kansas City Chiefs,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0
4,5,10,9,1960,-1,0,1,Tennessee Titans,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,12,2021,-1,0,0,New Orleans Saints,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0
945,15,12,19,2021,-1,0,1,Miami Dolphins,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0
946,16,12,26,2021,1,0,0,Jacksonville Jaguars,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0
947,17,1,2,2022,-1,0,0,Tampa Bay Buccaneers,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0
948,18,1,9,2022,-1,0,1,Buffalo Bills,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0

In [31]:
df.Month.unique()

array([ 9, 10, 11, 12,  1,  8])

In [32]:
df = pd.get_dummies(df[['Week_of_Season','Month','Day_of_Month',
                        'Year','Win','OT','Away','Opp',
                        'Score_Tm','Score_Opp','Off_1stD',
                        'Off_TotYd','Off_PassY','Off_RushY',
                        'Off_TO','Def_1stD','Def_TotYd',
                        'Def_PassY','Def_RushY','Def_TO']],
              columns = ['Opp'])

df

,Week_of_Season,Month,Day_of_Month,Year,Win,OT,Away,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Opp_Arizona Cardinals,Opp_Atlanta Falcons,Opp_Baltimore Ravens,Opp_Buffalo Bills,Opp_Carolina Panthers,Opp_Chicago Bears,Opp_Cincinnati Bengals,Opp_Cleveland Browns,Opp_Dallas Cowboys,Opp_Denver Broncos,Opp_Detroit Lions,Opp_Green Bay Packers,Opp_Houston Texans,Opp_Indianapolis Colts,Opp_Jacksonville Jaguars,Opp_Kansas City Chiefs,Opp_Las Vegas Raiders,Opp_Los Angeles Chargers,Opp_Los Angeles Rams,Opp_Miami Dolphins,Opp_Minnesota Vikings,Opp_New England Patriots,Opp_New Orleans Saints,Opp_New York Giants,Opp_Philadelphia Eagles,Opp_Pittsburgh Steelers,Opp_San Francisco 49ers,Opp_Seattle Seahawks,Opp_Tampa Bay Buccaneers,Opp_Tennessee Titans,Opp_Washington Commanders
0,1,9,11,1960,1,0,0,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,9,17,1960,-1,0,0,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,9,23,1960,1,0,0,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,10,2,1960,1,0,1,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,10,9,1960,-1,0,1,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,12,2021,-1,0,0,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
945,15,12,19,2021,-1,0,1,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
946,16,12,26,2021,1,0,0,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
947,17,1,2,2022,-1,0,0,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
948,18,1,9,2022,-1,0,1,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [33]:
df = df.rename(columns={'Opp_Arizona Cardinals':'Cardinals', 'Opp_Atlanta Falcons':'Falcons', 'Opp_Baltimore Ravens':'Ravens', 
           'Opp_Buffalo Bills':'Bills', 'Opp_Carolina Panthers':'Panthers', 'Opp_Chicago Bears':'Bears', 
           'Opp_Cincinnati Bengals':'Bengals', 'Opp_Cleveland Browns':'Browns', 'Opp_Dallas Cowboys':'Cowboys', 
           'Opp_Denver Broncos':'Broncos', 'Opp_Detroit Lions':'Lions', 'Opp_Green Bay Packers':'Packers',
           'Opp_Houston Texans':'Texans', 'Opp_Indianapolis Colts':'Colts', 'Opp_Jacksonville Jaguars':'Jaguars',
           'Opp_Kansas City Chiefs':'Chiefs', 'Opp_Las Vegas Raiders':'Raiders', 'Opp_Los Angeles Chargers':'Chargers', 
           'Opp_Los Angeles Rams':'Rams', 'Opp_Miami Dolphins':'Dolphins', 'Opp_Minnesota Vikings':'Vikings', 
           'Opp_New England Patriots':'Patriots', 'Opp_New Orleans Saints':'Saints', 'Opp_New York Giants':'Giants', 
           'Opp_Philadelphia Eagles':'Eagles', 'Opp_Pittsburgh Steelers':'Steelers', 'Opp_San Francisco 49ers':'49ers',
           'Opp_Seattle Seahawks':'Seahawks', 'Opp_Tampa Bay Buccaneers':'Buccaneers', 'Opp_Tennessee Titans':'Titans',
           'Opp_Washington Commanders':'Commanders'}
         )
df

,Week_of_Season,Month,Day_of_Month,Year,Win,OT,Away,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Cardinals,Falcons,Ravens,Bills,Panthers,Bears,Bengals,Browns,Cowboys,Broncos,Lions,Packers,Texans,Colts,Jaguars,Chiefs,Raiders,Chargers,Rams,Dolphins,Vikings,Patriots,Saints,Giants,Eagles,Steelers,49ers,Seahawks,Buccaneers,Titans,Commanders
0,1,9,11,1960,1,0,0,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,9,17,1960,-1,0,0,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,9,23,1960,1,0,0,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,10,2,1960,1,0,1,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,10,9,1960,-1,0,1,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,12,2021,-1,0,0,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
945,15,12,19,2021,-1,0,1,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
946,16,12,26,2021,1,0,0,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
947,17,1,2,2022,-1,0,0,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
948,18,1,9,2022,-1,0,1,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Week_of_Season  949 non-null    object
 1   Month           949 non-null    int64
 2   Day_of_Month    949 non-null    object
 3   Year            949 non-null    int64
 4   Win             949 non-null    int64
 5   OT              949 non-null    int64
 6   Away            949 non-null    int64
 7   Score_Tm        949 non-null    float64
 8   Score_Opp       949 non-null    float64
 9   Off_1stD        949 non-null    float64
 10  Off_TotYd       949 non-null    float64
 11  Off_PassY       949 non-null    float64
 12  Off_RushY       949 non-null    float64
 13  Off_TO          949 non-null    float64
 14  Def_1stD        949 non-null    float64
 15  Def_TotYd       949 non-null    float64
 16  Def_PassY       949 non-null    float64
 17  Def_RushY       949 non-null    float64
 18  Def_TO          949 non-null    float64
 19  Cardinals       949 non-null    uint8
 20  Falcons         949 non-null    uint8
 21  Ravens          949 non-null    uint8
 22  Bills           949 non-null    uint8
 23  Panthers        949 non-null    uint8
 24  Bears           949 non-null    uint8
 25  Bengals         949 non-null    uint8
 26  Browns          949 non-null    uint8
 27  Cowboys         949 non-null    uint8
 28  Broncos         949 non-null    uint8
 29  Lions           949 non-null    uint8
 30  Packers         949 non-null    uint8
 31  Texans          949 non-null    uint8
 32  Colts           949 non-null    uint8
 33  Jaguars         949 non-null    uint8
 34  Chiefs          949 non-null    uint8
 35  Raiders         949 non-null    uint8
 36  Chargers        949 non-null    uint8
 37  Rams            949 non-null    uint8
 38  Dolphins        949 non-null    uint8
 39  Vikings         949 non-null    uint8
 40  Patriots        949 non-null    uint8
 41  Saints          949 non-null    uint8
 42  Giants          949 non-null    uint8
 43  Eagles          949 non-null    uint8
 44  Steelers        949 non-null    uint8
 45  49ers           949 non-null    uint8
 46  Seahawks        949 non-null    uint8
 47  Buccaneers      949 non-null    uint8
 48  Titans          949 non-null    uint8
 49  Commanders      949 non-null    uint8
dtypes: float64(12), int64(5), object(2), uint8(31)
memory usage: 169.7+ KB

In [35]:
#Ranges for data types
print(np.iinfo(np.int64).max)
print(np.iinfo(np.uint8).max)
print(np.iinfo(np.uint16).max)
print(np.finfo(np.float64).max)
print(np.finfo(np.float32).max)

9223372036854775807
255
65535
1.7976931348623157e+308
3.4028235e+38

In [36]:
df=df.astype({'Week_of_Season':'int64','Day_of_Month':'int64',})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Week_of_Season  949 non-null    int64
 1   Month           949 non-null    int64
 2   Day_of_Month    949 non-null    int64
 3   Year            949 non-null    int64
 4   Win             949 non-null    int64
 5   OT              949 non-null    int64
 6   Away            949 non-null    int64
 7   Score_Tm        949 non-null    float64
 8   Score_Opp       949 non-null    float64
 9   Off_1stD        949 non-null    float64
 10  Off_TotYd       949 non-null    float64
 11  Off_PassY       949 non-null    float64
 12  Off_RushY       949 non-null    float64
 13  Off_TO          949 non-null    float64
 14  Def_1stD        949 non-null    float64
 15  Def_TotYd       949 non-null    float64
 16  Def_PassY       949 non-null    float64
 17  Def_RushY       949 non-null    float64
 18  Def_TO          949 non-null    float64
 19  Cardinals       949 non-null    uint8
 20  Falcons         949 non-null    uint8
 21  Ravens          949 non-null    uint8
 22  Bills           949 non-null    uint8
 23  Panthers        949 non-null    uint8
 24  Bears           949 non-null    uint8
 25  Bengals         949 non-null    uint8
 26  Browns          949 non-null    uint8
 27  Cowboys         949 non-null    uint8
 28  Broncos         949 non-null    uint8
 29  Lions           949 non-null    uint8
 30  Packers         949 non-null    uint8
 31  Texans          949 non-null    uint8
 32  Colts           949 non-null    uint8
 33  Jaguars         949 non-null    uint8
 34  Chiefs          949 non-null    uint8
 35  Raiders         949 non-null    uint8
 36  Chargers        949 non-null    uint8
 37  Rams            949 non-null    uint8
 38  Dolphins        949 non-null    uint8
 39  Vikings         949 non-null    uint8
 40  Patriots        949 non-null    uint8
 41  Saints          949 non-null    uint8
 42  Giants          949 non-null    uint8
 43  Eagles          949 non-null    uint8
 44  Steelers        949 non-null    uint8
 45  49ers           949 non-null    uint8
 46  Seahawks        949 non-null    uint8
 47  Buccaneers      949 non-null    uint8
 48  Titans          949 non-null    uint8
 49  Commanders      949 non-null    uint8
dtypes: float64(12), int64(7), uint8(31)
memory usage: 169.7 KB

In [38]:
df

,Week_of_Season,Month,Day_of_Month,Year,Win,OT,Away,Score_Tm,Score_Opp,Off_1stD,Off_TotYd,Off_PassY,Off_RushY,Off_TO,Def_1stD,Def_TotYd,Def_PassY,Def_RushY,Def_TO,Cardinals,Falcons,Ravens,Bills,Panthers,Bears,Bengals,Browns,Cowboys,Broncos,Lions,Packers,Texans,Colts,Jaguars,Chiefs,Raiders,Chargers,Rams,Dolphins,Vikings,Patriots,Saints,Giants,Eagles,Steelers,49ers,Seahawks,Buccaneers,Titans,Commanders
0,1,9,11,1960,1,0,0,27.0,3.0,20.0,340.0,176.0,164.0,1.0,9.0,113.0,39.0,74.0,3.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,9,17,1960,-1,0,0,24.0,28.0,17.0,297.0,181.0,116.0,4.0,19.0,300.0,191.0,109.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,9,23,1960,1,0,0,28.0,24.0,17.0,274.0,90.0,184.0,2.0,25.0,413.0,204.0,209.0,2.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,10,2,1960,1,0,1,37.0,35.0,27.0,404.0,267.0,137.0,1.0,24.0,442.0,333.0,109.0,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,10,9,1960,-1,0,1,21.0,27.0,25.0,367.0,304.0,63.0,6.0,21.0,344.0,176.0,168.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,14,12,12,2021,-1,0,0,9.0,30.0,13.0,256.0,178.0,78.0,0.0,21.0,344.0,141.0,203.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
945,15,12,19,2021,-1,0,1,24.0,31.0,16.0,228.0,126.0,102.0,1.0,23.0,379.0,196.0,183.0,3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
946,16,12,26,2021,1,0,0,26.0,21.0,18.0,373.0,100.0,273.0,0.0,27.0,384.0,252.0,132.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
947,17,1,2,2022,-1,0,0,24.0,28.0,22.0,374.0,224.0,150.0,1.0,26.0,467.0,405.0,62.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
948,18,1,9,2022,-1,0,1,10.0,27.0,4.0,53.0,5.0,48.0,0.0,25.0,424.0,254.0,170.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0